name: NNCF

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "00 7 * * 6"  # Run every saturday on 7:00 UTC

jobs:
  test_nncf:
    name: "Tests"

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        transformers-version: [
          "transformers[torch]==4.9.1",
          "transformers[torch]==4.11.0",
          "transformers[torch]",
        ]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[nncf]
        python -m pip install ${{ matrix.transformers-version }}
        sudo apt-get install libsndfile1

    - name: Prepare examples
      working-directory: tests/nncf
      run: |
        ver=$(python -c "import transformers; print(transformers.__version__)")
        wget https://raw.githubusercontent.com/huggingface/transformers/v${ver}/examples/pytorch/token-classification/run_ner.py -P examples/pytorch/token-classification
        wget https://raw.githubusercontent.com/huggingface/transformers/v${ver}/examples/pytorch/token-classification/requirements.txt
        patch -p1 < run_ner.patch
        python -m pip install -r requirements.txt && rm requirements.txt

        wget https://raw.githubusercontent.com/huggingface/transformers/v4.15.0/examples/pytorch/audio-classification/run_audio_classification.py -P examples/pytorch/audio-classification
        wget https://raw.githubusercontent.com/huggingface/transformers/v4.15.0/examples/pytorch/audio-classification/requirements.txt
        patch -p1 < run_audio_classification.patch
        python -m pip install -r requirements.txt && rm requirements.txt
        python -m pip install torch==1.9.1

    - name: Test NNCF
      working-directory: tests/nncf
      run: |
        cp ../../optimum/intel/nncf/configs/* .
        python -m unittest
